### ISSUE TITLE
[fix]: Cannot compile in v3.0.0

### ISSUE THREAD

**Issue by seamile4kairi** [posthtml/posthtml-cli#252]
Hi.
I've installed the latest version, but the following error is displayed and HTML is not compiled.

```
{ _: [],
  version: false,
  v: false,
  h: false,
  help: false,
  o: 'dist/',
  output: 'dist/',
  i: [ 'src/**/*.html' ],
  input: [ 'src/**/*.html' ],
  c: 'posthtml.config.js',
  config: 'posthtml.config.js',
  '$0': '/PATH/TO/PROJECT/ROOT/node_modules/.bin/posthtml' }
(node:82379) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'post-load-plugins'
(node:82379) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My settings is here:

package.json
```
{
  ...
  "scripts": {
    ...
    "build:markup": "posthtml -i src/**/*.html -o dist/ -c posthtml.config.js",
    ...
  },
  "devDependencies": {
    ...
    "posthtml-cli": "^0.3.0",
    "posthtml-w3c": "^0.8.1",
    ...
  },
  ...
}
```

posthtml.config.js
```
module.exports = (ctx) => {
  return {
    from: ctx.from,
    to: ctx.to,
    plugins: {
      'posthtml-w3c': {}
    }
  }
};
```

I use the latest version of Node.js and npm on macOS Sierra.

**Comment by GitScrum** [comment]
@seamile4kairi Hi, thanks for feedback, Is associated with incorrect work `post-load-plugins`. I'm working on it. I recommend use options `--auto-off` for a while.

**Comment by seamile4kairi** [comment]
@GitScrum Thanks for your reply.
The following message is still returned, but now HTML file seems to be output correctly.

```
{ _: [],
  version: false,
  v: false,
  h: false,
  help: false,
  i: [ 'src/**/*.html' ],
  input: [ 'src/**/*.html' ],
  o: 'dist/',
  output: 'dist/',
  c: 'posthtml.config.js',
  config: 'posthtml.config.js',
  'auto-off': true,
  autoOff: true,
  '$0': '/PATH/TO/PROJECT/ROOT/node_modules/.bin/posthtml' }
```

Waiting for the bug fix in v0.3.1!

**Comment by GitScrum** [comment]
@seamile4kairi thanks for your feedback, now everything should work.

and you do not need to create a configuration file unless there is an additional option for plug-ins. See more information about [post-load-plugins](https://github.com/post-org/post-load-plugins#usage)
